### ISSUE TITLE
Plasma-Wallpaper-DreamDesktop available for KDE 5?

### ISSUE THREAD

**Issue by kuboosoft** [jarzebski/Plasma-Wallpaper-DreamDesktop#2]
Hi, will available Plasma-Wallpaper-DreamDesktop for KDE 5? I Love it!

**Comment by jarzebski** [comment]
Hello, sorry but DD is not developed :(
Regards
Korneliusz

W dniu 05/24/2015 o 04:37 AM, kuboosoft pisze:
