### ISSUE TITLE
Erro - Cmake?

### ISSUE THREAD

**Issue by Kaiserdragon** [jarzebski/Plasma-Wallpaper-DreamDesktop#4]
Hello everyone!

I use Fedora 22 (x64) + KDE...
I've got the following error.

---

[root@localhost build]# cmake .. -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix`
CMake Error at /usr/share/cmake/Modules/FindKDE4.cmake:111 (message):
  ERROR: cmake/modules/FindKDE4Internal.cmake not found in
  /root/.kde/share/apps;/usr/share/kde-settings/kde-profile/default/share/apps;/usr/share/kde4/apps
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

```
cmake_minimum_required(VERSION 3.2)
```

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/jr/Downloads/Plasma-Wallpaper-DreamDesktop-master/build/CMakeFiles/CMakeOutput.log".
[root@localhost build]#

**Comment by Drezil** [comment]
Made a version that compiles for me: https://github.com/Drezil/Plasma-Wallpaper-DreamDesktop

had to install libavcodec-dev libavformat-dev libavutiv-dev kdelibs5-dev kde-ẁorkspace-dev for it to compile under Kubuntu 14.04
